<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.3.0" />
    <PackageReference Include="Serilog.Sinks.PostgreSQL.Configuration" Version="1.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Wkhtmltopdf.NetCore" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers/Facturacion/" />
    <Folder Include="Controllers/Security/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../2-Application/Seguridad.Application/Seguridad.Application.csproj" />
    <ProjectReference Include="..\..\Common.Utilities\Common.Utilities.csproj" />
    <ProjectReference Include="..\..\4-Domain\Inventory.Domain\Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\2-Application\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="..\..\4-Domain\Seguridad.Domain\Seguridad.Domain.csproj" />
    </ItemGroup>

</Project>
