-- Dispositivos de confianza: permite saltar el TOTP en logins posteriores
-- desde el mismo navegador/dispositivo durante un tiempo configurable
-- (JwtSettings:TrustedDeviceDays), tras haber verificado el 2FA una vez.
--
-- Mismo criterio que sec.refresh_tokens: nunca se guarda el token en claro,
-- solo su hash SHA-512, y la tabla queda fuera de RLS porque se consulta en
-- pleno flujo de autenticación, antes de resolver el tenant, siempre por
-- user_id o por hash (nunca filtrada por tenant_id).
--
-- Idempotente: se puede correr más de una vez sin efectos secundarios.

CREATE TABLE IF NOT EXISTS sec.trusted_devices (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer      NOT NULL,
    token_hash   varchar(128) NOT NULL,
    device_label varchar(400) NOT NULL DEFAULT '',
    created_at   timestamptz  NOT NULL DEFAULT now(),
    expires_at   timestamptz  NOT NULL,
    revoked_at   timestamptz
);

-- Búsqueda por hash en cada login.
CREATE UNIQUE INDEX IF NOT EXISTS ix_trusted_devices_hash
    ON sec.trusted_devices (token_hash);

-- Revocación masiva por usuario (cambio de contraseña, reset de MFA).
CREATE INDEX IF NOT EXISTS ix_trusted_devices_user
    ON sec.trusted_devices (user_id) WHERE revoked_at IS NULL;
