server {
    listen 80;
    server_name localhost; # Puede ser cualquier cosa, ya que Nginx en el host se encargará del dominio

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; # IMPORTANTE para el Vue Router (modo history)
    }

    # Si necesitas API u otros servicios en otro contenedor/servidor:
    # location /api/ {
    #     proxy_pass http://<ip_o_nombre_del_contenedor_api>:port/;
    # }
}