-- Tabla de refresh tokens: permite mantener la sesión móvil abierta durante
-- semanas sin volver a pedir contraseña + 2FA, y a la vez poder revocarla.
--
-- El JWT es autocontenido y por tanto irrevocable hasta que expira; el refresh
-- token vive aquí, así que desactivar un usuario o marcar la fila como revocada
-- corta el acceso en cuanto vence el access token (minutos, no días).
--
-- Nunca se guarda el token en claro: solo su hash SHA-512. Quien lea la tabla
-- no puede reconstruir el token original.
--
-- Ejecutar una vez sobre la base en uso (punto_venta en desarrollo,
-- punto_venta_pg según el appsettings de producción).

CREATE TABLE IF NOT EXISTS sec.refresh_tokens (
    -- A diferencia del resto del esquema no se usa sequences_key: esa función
    -- bloquea una fila contador en cada inserción (se serializarían todos los
    -- refresh concurrentes) y es susceptible de desincronizarse. Una identidad
    -- nativa no tiene ninguno de los dos problemas.
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer      NOT NULL,
    token_hash  varchar(128) NOT NULL,
    device      varchar(400) NOT NULL DEFAULT '',
    login_from  varchar(50)  NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    expires_at  timestamptz  NOT NULL,
    revoked_at  timestamptz,
    -- Id del token que lo reemplazó al rotar. Sirve para detectar reuso.
    replaced_by bigint
);

-- Búsqueda por hash en cada refresh.
CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_hash
    ON sec.refresh_tokens (token_hash);

-- Revocación masiva por usuario (baja de empleado, reuso detectado).
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user
    ON sec.refresh_tokens (user_id) WHERE revoked_at IS NULL;
